
# -*- mode: ruby -*-
# vi: set ft=ruby :

$install_consul = <<SCRIPT
echo "Installing dependencies ..."
sudo apt-get update
sudo apt-get install -y unzip curl jq dnsutils
echo "Determining Consul version to install ..."
CHECKPOINT_URL="https://checkpoint-api.hashicorp.com/v1/check"
if [ -z "$CONSUL_DEMO_VERSION" ]; then
    CONSUL_DEMO_VERSION=$(curl -s "${CHECKPOINT_URL}"/consul | jq .current_version | tr -d '"')
fi
echo "Fetching Consul version ${CONSUL_DEMO_VERSION} ..."
cd /tmp/
curl -s https://releases.hashicorp.com/consul/${CONSUL_DEMO_VERSION}/consul_${CONSUL_DEMO_VERSION}_linux_amd64.zip -o consul.zip
echo "Installing Consul version ${CONSUL_DEMO_VERSION} ..."
unzip consul.zip
sudo chmod +x consul
sudo mv consul /usr/bin/consul
sudo mkdir /etc/consul.d
sudo chmod a+w /etc/consul.d
SCRIPT

# script that runs consul server agent, wasn't able to use it because after the command is run
# the terminal can't accept more commands
$consul_client_agent = <<SCRIPT
consul agent -data-dir=/tmp/consul -bind=172.20.20.11 -config-dir=/etc/consul.d
SCRIPT

# script that runs consul client agent, wasn't able to use it because after the command is run
# the terminal can't accept more commands
$consul_server_agent = <<SCRIPT
consul agent -server -bootstrap-expect=1 -bind=172.20.20.10 -data-dir=/tmp/consul -config-dir=/etc/consul.d
SCRIPT

$install_apache = <<SCRIPT
vagrant ssh apache-server-and-consul-agent
sudo apt update
sudo apt install -y apache2
SCRIPT


Vagrant.configure("2") do |config|
  
  config.vm.provision "shell", inline: $install_consul
  
  config.vm.define "consul-server" do |cs|
    cs.vm.hostname = "consul-server"
    cs.vm.network "private_network", ip: "172.20.20.10", virtualbox__intnet: true, auto_config: true
    cs.vm.box = "bento/ubuntu-20.04"
    cs.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
    # cs.vm.provision "shell", inline: $consul_server_agent
  end

  config.vm.define "apache-server-and-consul-agent" do |asca|
    asca.vm.hostname = "apache-server-and-consul-agent"
    asca.vm.network "private_network", ip: "172.20.20.11", virtualbox__intnet: true, auto_config: true
    asca.vm.box = "bento/ubuntu-20.04"
    asca.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
    asca.vm.network "forwarded_port", guest: 80, host: 8080
    asca.vm.provision "shell", inline: $install_apache
    # asca.vm.provision "shell", inline: $consul_client_agent
  end
end
